apiVersion: v1
kind: Service
metadata:
  name: mysql-ext
spec:
  type: LoadBalancer
  ports:
  - port: 13306
    name: mysql
    targetPort: 13306
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: mysql-tcp